= About This Repository

This repository contains the TEI source file, and derived text and HTML files of an ebook posted to https://www.gutenberg.org/[Project Gutenberg]. Like the version posted to Project Gutenberg, this ebook is free from copyright in the U.S. No claim is made about its copyright status outside the U.S.

The version maintained in this repository may be slightly out-of-sync with the version maintained at Project Gutenberg. Mostly, fixes will be made first here, and only then reposted to Project Gutenberg. When you encounter any issue in this text, please report it here.

== About This Ebook

|===
|Field |Value

|Title |Folk tales from Tibet
|Author |William Frederick Travers O’Connor (1870–1943)
|Publisher |Project Gutenberg, Urbana, Illinois, USA., 2024-12-30
|Publication date |2024-12-30
|Availability |This eBook is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gutenberg License included with this eBook or online at https://www.gutenberg.org/[www.gutenberg.org]. This eBook is produced by the Online Distributed Proofreading Team at https://www.pgdp.net/[www.pgdp.net].
|PG Ebook Number |https://www.gutenberg.org/ebooks/75000[75000]
|===
